/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations.async;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.io.InputStream;
import java.lang.Override;
import java.lang.String;
import java.net.http.HttpResponse;
import java.util.Optional;
import org.openapis.openapi.models.operations.ExtractBookmarksResponseBody;
import org.openapis.openapi.utils.AsyncResponse;
import org.openapis.openapi.utils.Blob;
import org.openapis.openapi.utils.Utils;


public class ExtractBookmarksResponse implements AsyncResponse {
    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<Blob> rawResponse;

    /**
     * Analysis or data extraction completed successfully
     */
    private ExtractBookmarksResponseBody object;

    @JsonCreator
    public ExtractBookmarksResponse(
            @Nonnull String contentType,
            int statusCode,
            @Nonnull HttpResponse<Blob> rawResponse,
            @Nullable ExtractBookmarksResponseBody object) {
        this.contentType = Optional.ofNullable(contentType)
            .orElseThrow(() -> new IllegalArgumentException("contentType cannot be null"));
        this.statusCode = statusCode;
        this.rawResponse = Optional.ofNullable(rawResponse)
            .orElseThrow(() -> new IllegalArgumentException("rawResponse cannot be null"));
        this.object = object;
    }
    
    public ExtractBookmarksResponse(
            @Nonnull String contentType,
            int statusCode,
            @Nonnull HttpResponse<Blob> rawResponse) {
        this(contentType, statusCode, rawResponse,
            null);
    }

    /**
     * HTTP response content type for this operation
     */
    public String contentType() {
        return this.contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    public int statusCode() {
        return this.statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public HttpResponse<Blob> rawResponse() {
        return this.rawResponse;
    }

    /**
     * Analysis or data extraction completed successfully
     */
    public Optional<ExtractBookmarksResponseBody> object() {
        return Optional.ofNullable(this.object);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * HTTP response content type for this operation
     */
    public ExtractBookmarksResponse withContentType(@Nonnull String contentType) {
        this.contentType = Utils.checkNotNull(contentType, "contentType");
        return this;
    }


    /**
     * HTTP response status code for this operation
     */
    public ExtractBookmarksResponse withStatusCode(int statusCode) {
        this.statusCode = statusCode;
        return this;
    }


    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public ExtractBookmarksResponse withRawResponse(@Nonnull HttpResponse<Blob> rawResponse) {
        this.rawResponse = Utils.checkNotNull(rawResponse, "rawResponse");
        return this;
    }


    /**
     * Analysis or data extraction completed successfully
     */
    public ExtractBookmarksResponse withObject(@Nullable ExtractBookmarksResponseBody object) {
        this.object = object;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ExtractBookmarksResponse other = (ExtractBookmarksResponse) o;
        return 
            Utils.enhancedDeepEquals(this.contentType, other.contentType) &&
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse) &&
            Utils.enhancedDeepEquals(this.object, other.object);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            contentType, statusCode, rawResponse,
            object);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ExtractBookmarksResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "object", object);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String contentType;

        private int statusCode;

        private HttpResponse<Blob> rawResponse;

        private ExtractBookmarksResponseBody object;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(@Nonnull String contentType) {
            this.contentType = Utils.checkNotNull(contentType, "contentType");
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(@Nonnull HttpResponse<Blob> rawResponse) {
            this.rawResponse = Utils.checkNotNull(rawResponse, "rawResponse");
            return this;
        }

        /**
         * Analysis or data extraction completed successfully
         */
        public Builder object(@Nullable ExtractBookmarksResponseBody object) {
            this.object = object;
            return this;
        }

        public ExtractBookmarksResponse build() {
            return new ExtractBookmarksResponse(
                contentType, statusCode, rawResponse,
                object);
        }

    }
}
