/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations.async;

import static org.openapis.openapi.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nullable;
import java.util.concurrent.CompletableFuture;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.components.MetadataRequest;
import org.openapis.openapi.operations.Metadata;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Utils;

public class MetadataRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private MetadataRequest request;

    public MetadataRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public MetadataRequestBuilder request(@Nullable MetadataRequest request) {
        this.request = request;
        return this;
    }

    private MetadataRequest _buildRequest() {
        return this.request;
    }
    
    public MetadataRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<MetadataResponse> call() {
        AsyncRequestOperation<MetadataRequest, MetadataResponse> operation
              = new Metadata.Async(sdkConfiguration, _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
