/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nullable;
import java.lang.Exception;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.components.AddPasswordRequest;
import org.openapis.openapi.operations.AddPassword;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Utils;

public class AddPasswordRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private AddPasswordRequest request;

    public AddPasswordRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public AddPasswordRequestBuilder request(@Nullable AddPasswordRequest request) {
        this.request = request;
        return this;
    }

    private AddPasswordRequest _buildRequest() {
        return this.request;
    }
    
    public AddPasswordRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public AddPasswordResponse call() throws Exception {
        RequestOperation<AddPasswordRequest, AddPasswordResponse> operation
              = new AddPassword.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
