/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nullable;
import java.lang.Exception;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.components.SplitPdfBySizeOrCountRequest;
import org.openapis.openapi.operations.AutoSplitPdf1;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Utils;

public class AutoSplitPdf1RequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private SplitPdfBySizeOrCountRequest request;

    public AutoSplitPdf1RequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public AutoSplitPdf1RequestBuilder request(@Nullable SplitPdfBySizeOrCountRequest request) {
        this.request = request;
        return this;
    }

    private SplitPdfBySizeOrCountRequest _buildRequest() {
        return this.request;
    }
    
    public AutoSplitPdf1RequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public AutoSplitPdf1Response call() throws Exception {
        RequestOperation<SplitPdfBySizeOrCountRequest, AutoSplitPdf1Response> operation
              = new AutoSplitPdf1.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
