/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nullable;
import java.lang.Exception;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.components.EditTableOfContentsRequest;
import org.openapis.openapi.operations.EditTableOfContents;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Utils;

public class EditTableOfContentsRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private EditTableOfContentsRequest request;

    public EditTableOfContentsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public EditTableOfContentsRequestBuilder request(@Nullable EditTableOfContentsRequest request) {
        this.request = request;
        return this;
    }

    private EditTableOfContentsRequest _buildRequest() {
        return this.request;
    }
    
    public EditTableOfContentsRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public EditTableOfContentsResponse call() throws Exception {
        RequestOperation<EditTableOfContentsRequest, EditTableOfContentsResponse> operation
              = new EditTableOfContents.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
