/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nullable;
import java.lang.Exception;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.components.ExtractImageScansRequest;
import org.openapis.openapi.operations.ExtractImageScans;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Utils;

public class ExtractImageScansRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private ExtractImageScansRequest request;

    public ExtractImageScansRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public ExtractImageScansRequestBuilder request(@Nullable ExtractImageScansRequest request) {
        this.request = request;
        return this;
    }

    private ExtractImageScansRequest _buildRequest() {
        return this.request;
    }
    
    public ExtractImageScansRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public ExtractImageScansResponse call() throws Exception {
        RequestOperation<ExtractImageScansRequest, ExtractImageScansResponse> operation
              = new ExtractImageScans.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
