/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nullable;
import java.lang.Exception;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.operations.ExtractBookmarks;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Utils;

public class ExtractBookmarksRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private ExtractBookmarksRequest request;

    public ExtractBookmarksRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public ExtractBookmarksRequestBuilder request(@Nullable ExtractBookmarksRequest request) {
        this.request = request;
        return this;
    }

    private ExtractBookmarksRequest _buildRequest() {
        return this.request;
    }
    
    public ExtractBookmarksRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public ExtractBookmarksResponse call() throws Exception {
        RequestOperation<ExtractBookmarksRequest, ExtractBookmarksResponse> operation
              = new ExtractBookmarks.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
