/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestlessOperation;

import java.lang.Exception;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.operations.GetDatabaseData;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Utils;

public class GetDatabaseDataRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();

    public GetDatabaseDataRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    
    public GetDatabaseDataRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public GetDatabaseDataResponse call() throws Exception {
        RequestlessOperation<GetDatabaseDataResponse> operation
            = new GetDatabaseData.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest());
    }
}
