/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import java.lang.Override;
import java.lang.String;
import org.openapis.openapi.utils.Utils;

/**
 * GetPdfInfoResponseBody
 * 
 * <p>JSON object containing the requested data or analysis results
 */
public class GetPdfInfoResponseBody {
    @JsonCreator
    public GetPdfInfoResponseBody() {
    }

    public static Builder builder() {
        return new Builder();
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        return true;
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            );
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetPdfInfoResponseBody.class);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Builder() {
          // force use of static builder() method
        }

        public GetPdfInfoResponseBody build() {
            return new GetPdfInfoResponseBody(
                );
        }

    }
}
