/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import java.lang.Exception;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.operations.GetTeamDetailsData;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Utils;

public class GetTeamDetailsDataRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final GetTeamDetailsDataRequest.Builder pojoBuilder;
    private GetTeamDetailsDataRequest request;
    private boolean _setterCalled;

    public GetTeamDetailsDataRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = GetTeamDetailsDataRequest.builder();
    }

    public GetTeamDetailsDataRequestBuilder id(long id) {
        this.pojoBuilder.id(id);
        this._setterCalled = true;
        return this;
    }

    private GetTeamDetailsDataRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public GetTeamDetailsDataRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public GetTeamDetailsDataResponse call() throws Exception {
        RequestOperation<GetTeamDetailsDataRequest, GetTeamDetailsDataResponse> operation
              = new GetTeamDetailsData.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
