/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nullable;
import java.lang.Exception;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.components.PDFComparisonAndCount;
import org.openapis.openapi.operations.PageCount;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Utils;

public class PageCountRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private PDFComparisonAndCount request;

    public PageCountRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public PageCountRequestBuilder request(@Nullable PDFComparisonAndCount request) {
        this.request = request;
        return this;
    }

    private PDFComparisonAndCount _buildRequest() {
        return this.request;
    }
    
    public PageCountRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public PageCountResponse call() throws Exception {
        RequestOperation<PDFComparisonAndCount, PageCountResponse> operation
              = new PageCount.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
