/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nullable;
import java.lang.Exception;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.components.PDFFile;
import org.openapis.openapi.operations.PdfToSinglePage;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Utils;

public class PdfToSinglePageRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private PDFFile request;

    public PdfToSinglePageRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public PdfToSinglePageRequestBuilder request(@Nullable PDFFile request) {
        this.request = request;
        return this;
    }

    private PDFFile _buildRequest() {
        return this.request;
    }
    
    public PdfToSinglePageRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public PdfToSinglePageResponse call() throws Exception {
        RequestOperation<PDFFile, PdfToSinglePageResponse> operation
              = new PdfToSinglePage.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
