/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nullable;
import java.lang.Exception;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.components.GeneralFile;
import org.openapis.openapi.operations.ProcessFileToPDF;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Utils;

public class ProcessFileToPDFRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private GeneralFile request;

    public ProcessFileToPDFRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public ProcessFileToPDFRequestBuilder request(@Nullable GeneralFile request) {
        this.request = request;
        return this;
    }

    private GeneralFile _buildRequest() {
        return this.request;
    }
    
    public ProcessFileToPDFRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public ProcessFileToPDFResponse call() throws Exception {
        RequestOperation<GeneralFile, ProcessFileToPDFResponse> operation
              = new ProcessFileToPDF.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
