/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nullable;
import java.lang.Exception;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.components.SanitizePdfRequest;
import org.openapis.openapi.operations.SanitizePDF;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Utils;

public class SanitizePDFRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private SanitizePdfRequest request;

    public SanitizePDFRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public SanitizePDFRequestBuilder request(@Nullable SanitizePdfRequest request) {
        this.request = request;
        return this;
    }

    private SanitizePdfRequest _buildRequest() {
        return this.request;
    }
    
    public SanitizePDFRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public SanitizePDFResponse call() throws Exception {
        RequestOperation<SanitizePdfRequest, SanitizePDFResponse> operation
              = new SanitizePDF.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
