/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nullable;
import java.lang.Exception;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.components.ScalePagesRequest;
import org.openapis.openapi.operations.ScalePages;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Utils;

public class ScalePagesRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private ScalePagesRequest request;

    public ScalePagesRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public ScalePagesRequestBuilder request(@Nullable ScalePagesRequest request) {
        this.request = request;
        return this;
    }

    private ScalePagesRequest _buildRequest() {
        return this.request;
    }
    
    public ScalePagesRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public ScalePagesResponse call() throws Exception {
        RequestOperation<ScalePagesRequest, ScalePagesResponse> operation
              = new ScalePages.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
