/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nullable;
import java.lang.Exception;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.components.ScannerEffectRequest;
import org.openapis.openapi.operations.ScannerEffect;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Utils;

public class ScannerEffectRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private ScannerEffectRequest request;

    public ScannerEffectRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public ScannerEffectRequestBuilder request(@Nullable ScannerEffectRequest request) {
        this.request = request;
        return this;
    }

    private ScannerEffectRequest _buildRequest() {
        return this.request;
    }
    
    public ScannerEffectRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public ScannerEffectResponse call() throws Exception {
        RequestOperation<ScannerEffectRequest, ScannerEffectResponse> operation
              = new ScannerEffect.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
