/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nullable;
import java.lang.Exception;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.components.SplitPdfByChaptersRequest;
import org.openapis.openapi.operations.SplitPdf1;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Utils;

public class SplitPdf1RequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private SplitPdfByChaptersRequest request;

    public SplitPdf1RequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public SplitPdf1RequestBuilder request(@Nullable SplitPdfByChaptersRequest request) {
        this.request = request;
        return this;
    }

    private SplitPdfByChaptersRequest _buildRequest() {
        return this.request;
    }
    
    public SplitPdf1RequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public SplitPdf1Response call() throws Exception {
        RequestOperation<SplitPdfByChaptersRequest, SplitPdf1Response> operation
              = new SplitPdf1.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
