/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.io.InputStream;
import java.lang.Override;
import java.lang.String;
import java.net.http.HttpResponse;
import java.util.Optional;
import org.openapis.openapi.utils.Response;
import org.openapis.openapi.utils.Utils;


public class SplitPdf2Response implements Response {
    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * Files processed successfully. Returns single file or ZIP archive containing multiple files.
     */
    private InputStream twoHundredApplicationPdfResponseStream;

    /**
     * Files processed successfully. Returns single file or ZIP archive containing multiple files.
     */
    private InputStream twoHundredApplicationZipResponseStream;

    /**
     * Files processed successfully. Returns single file or ZIP archive containing multiple files.
     */
    private InputStream twoHundredImagePngResponseStream;

    /**
     * Files processed successfully. Returns single file or ZIP archive containing multiple files.
     */
    private InputStream twoHundredImageJpegResponseStream;

    @JsonCreator
    public SplitPdf2Response(
            @Nonnull String contentType,
            int statusCode,
            @Nonnull HttpResponse<InputStream> rawResponse,
            @Nullable InputStream twoHundredApplicationPdfResponseStream,
            @Nullable InputStream twoHundredApplicationZipResponseStream,
            @Nullable InputStream twoHundredImagePngResponseStream,
            @Nullable InputStream twoHundredImageJpegResponseStream) {
        this.contentType = Optional.ofNullable(contentType)
            .orElseThrow(() -> new IllegalArgumentException("contentType cannot be null"));
        this.statusCode = statusCode;
        this.rawResponse = Optional.ofNullable(rawResponse)
            .orElseThrow(() -> new IllegalArgumentException("rawResponse cannot be null"));
        this.twoHundredApplicationPdfResponseStream = twoHundredApplicationPdfResponseStream;
        this.twoHundredApplicationZipResponseStream = twoHundredApplicationZipResponseStream;
        this.twoHundredImagePngResponseStream = twoHundredImagePngResponseStream;
        this.twoHundredImageJpegResponseStream = twoHundredImageJpegResponseStream;
    }
    
    public SplitPdf2Response(
            @Nonnull String contentType,
            int statusCode,
            @Nonnull HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse,
            null, null, null,
            null);
    }

    /**
     * HTTP response content type for this operation
     */
    public String contentType() {
        return this.contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    public int statusCode() {
        return this.statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public HttpResponse<InputStream> rawResponse() {
        return this.rawResponse;
    }

    /**
     * Files processed successfully. Returns single file or ZIP archive containing multiple files.
     */
    public Optional<InputStream> twoHundredApplicationPdfResponseStream() {
        return Optional.ofNullable(this.twoHundredApplicationPdfResponseStream);
    }

    /**
     * Files processed successfully. Returns single file or ZIP archive containing multiple files.
     */
    public Optional<InputStream> twoHundredApplicationZipResponseStream() {
        return Optional.ofNullable(this.twoHundredApplicationZipResponseStream);
    }

    /**
     * Files processed successfully. Returns single file or ZIP archive containing multiple files.
     */
    public Optional<InputStream> twoHundredImagePngResponseStream() {
        return Optional.ofNullable(this.twoHundredImagePngResponseStream);
    }

    /**
     * Files processed successfully. Returns single file or ZIP archive containing multiple files.
     */
    public Optional<InputStream> twoHundredImageJpegResponseStream() {
        return Optional.ofNullable(this.twoHundredImageJpegResponseStream);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * HTTP response content type for this operation
     */
    public SplitPdf2Response withContentType(@Nonnull String contentType) {
        this.contentType = Utils.checkNotNull(contentType, "contentType");
        return this;
    }


    /**
     * HTTP response status code for this operation
     */
    public SplitPdf2Response withStatusCode(int statusCode) {
        this.statusCode = statusCode;
        return this;
    }


    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public SplitPdf2Response withRawResponse(@Nonnull HttpResponse<InputStream> rawResponse) {
        this.rawResponse = Utils.checkNotNull(rawResponse, "rawResponse");
        return this;
    }


    /**
     * Files processed successfully. Returns single file or ZIP archive containing multiple files.
     */
    public SplitPdf2Response withTwoHundredApplicationPdfResponseStream(@Nullable InputStream twoHundredApplicationPdfResponseStream) {
        this.twoHundredApplicationPdfResponseStream = twoHundredApplicationPdfResponseStream;
        return this;
    }


    /**
     * Files processed successfully. Returns single file or ZIP archive containing multiple files.
     */
    public SplitPdf2Response withTwoHundredApplicationZipResponseStream(@Nullable InputStream twoHundredApplicationZipResponseStream) {
        this.twoHundredApplicationZipResponseStream = twoHundredApplicationZipResponseStream;
        return this;
    }


    /**
     * Files processed successfully. Returns single file or ZIP archive containing multiple files.
     */
    public SplitPdf2Response withTwoHundredImagePngResponseStream(@Nullable InputStream twoHundredImagePngResponseStream) {
        this.twoHundredImagePngResponseStream = twoHundredImagePngResponseStream;
        return this;
    }


    /**
     * Files processed successfully. Returns single file or ZIP archive containing multiple files.
     */
    public SplitPdf2Response withTwoHundredImageJpegResponseStream(@Nullable InputStream twoHundredImageJpegResponseStream) {
        this.twoHundredImageJpegResponseStream = twoHundredImageJpegResponseStream;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SplitPdf2Response other = (SplitPdf2Response) o;
        return 
            Utils.enhancedDeepEquals(this.contentType, other.contentType) &&
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse) &&
            Utils.enhancedDeepEquals(this.twoHundredApplicationPdfResponseStream, other.twoHundredApplicationPdfResponseStream) &&
            Utils.enhancedDeepEquals(this.twoHundredApplicationZipResponseStream, other.twoHundredApplicationZipResponseStream) &&
            Utils.enhancedDeepEquals(this.twoHundredImagePngResponseStream, other.twoHundredImagePngResponseStream) &&
            Utils.enhancedDeepEquals(this.twoHundredImageJpegResponseStream, other.twoHundredImageJpegResponseStream);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            contentType, statusCode, rawResponse,
            twoHundredApplicationPdfResponseStream, twoHundredApplicationZipResponseStream, twoHundredImagePngResponseStream,
            twoHundredImageJpegResponseStream);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SplitPdf2Response.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "twoHundredApplicationPdfResponseStream", twoHundredApplicationPdfResponseStream,
                "twoHundredApplicationZipResponseStream", twoHundredApplicationZipResponseStream,
                "twoHundredImagePngResponseStream", twoHundredImagePngResponseStream,
                "twoHundredImageJpegResponseStream", twoHundredImageJpegResponseStream);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String contentType;

        private int statusCode;

        private HttpResponse<InputStream> rawResponse;

        private InputStream twoHundredApplicationPdfResponseStream;

        private InputStream twoHundredApplicationZipResponseStream;

        private InputStream twoHundredImagePngResponseStream;

        private InputStream twoHundredImageJpegResponseStream;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(@Nonnull String contentType) {
            this.contentType = Utils.checkNotNull(contentType, "contentType");
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(@Nonnull HttpResponse<InputStream> rawResponse) {
            this.rawResponse = Utils.checkNotNull(rawResponse, "rawResponse");
            return this;
        }

        /**
         * Files processed successfully. Returns single file or ZIP archive containing multiple files.
         */
        public Builder twoHundredApplicationPdfResponseStream(@Nullable InputStream twoHundredApplicationPdfResponseStream) {
            this.twoHundredApplicationPdfResponseStream = twoHundredApplicationPdfResponseStream;
            return this;
        }

        /**
         * Files processed successfully. Returns single file or ZIP archive containing multiple files.
         */
        public Builder twoHundredApplicationZipResponseStream(@Nullable InputStream twoHundredApplicationZipResponseStream) {
            this.twoHundredApplicationZipResponseStream = twoHundredApplicationZipResponseStream;
            return this;
        }

        /**
         * Files processed successfully. Returns single file or ZIP archive containing multiple files.
         */
        public Builder twoHundredImagePngResponseStream(@Nullable InputStream twoHundredImagePngResponseStream) {
            this.twoHundredImagePngResponseStream = twoHundredImagePngResponseStream;
            return this;
        }

        /**
         * Files processed successfully. Returns single file or ZIP archive containing multiple files.
         */
        public Builder twoHundredImageJpegResponseStream(@Nullable InputStream twoHundredImageJpegResponseStream) {
            this.twoHundredImageJpegResponseStream = twoHundredImageJpegResponseStream;
            return this;
        }

        public SplitPdf2Response build() {
            return new SplitPdf2Response(
                contentType, statusCode, rawResponse,
                twoHundredApplicationPdfResponseStream, twoHundredApplicationZipResponseStream, twoHundredImagePngResponseStream,
                twoHundredImageJpegResponseStream);
        }

    }
}
