/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nullable;
import java.lang.Exception;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.components.PDFWithPageNums;
import org.openapis.openapi.operations.SplitPdf2;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Utils;

public class SplitPdf2RequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private PDFWithPageNums request;

    public SplitPdf2RequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public SplitPdf2RequestBuilder request(@Nullable PDFWithPageNums request) {
        this.request = request;
        return this;
    }

    private PDFWithPageNums _buildRequest() {
        return this.request;
    }
    
    public SplitPdf2RequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public SplitPdf2Response call() throws Exception {
        RequestOperation<PDFWithPageNums, SplitPdf2Response> operation
              = new SplitPdf2.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
