/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nullable;
import java.lang.Exception;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.components.SignatureValidationRequest;
import org.openapis.openapi.operations.ValidateSignature;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Utils;

public class ValidateSignatureRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private SignatureValidationRequest request;

    public ValidateSignatureRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public ValidateSignatureRequestBuilder request(@Nullable SignatureValidationRequest request) {
        this.request = request;
        return this;
    }

    private SignatureValidationRequest _buildRequest() {
        return this.request;
    }
    
    public ValidateSignatureRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public ValidateSignatureResponse call() throws Exception {
        RequestOperation<SignatureValidationRequest, ValidateSignatureResponse> operation
              = new ValidateSignature.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
