/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi;

import static org.openapis.openapi.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nullable;
import java.util.concurrent.CompletableFuture;
import org.openapis.openapi.models.components.ContainsTextRequest;
import org.openapis.openapi.models.components.FileSizeRequest;
import org.openapis.openapi.models.components.PDFComparisonAndCount;
import org.openapis.openapi.models.components.PDFWithPageNums;
import org.openapis.openapi.models.components.PageRotationRequest;
import org.openapis.openapi.models.components.PageSizeRequest;
import org.openapis.openapi.models.operations.async.ContainsImageRequestBuilder;
import org.openapis.openapi.models.operations.async.ContainsImageResponse;
import org.openapis.openapi.models.operations.async.ContainsTextRequestBuilder;
import org.openapis.openapi.models.operations.async.ContainsTextResponse;
import org.openapis.openapi.models.operations.async.FileSizeRequestBuilder;
import org.openapis.openapi.models.operations.async.FileSizeResponse;
import org.openapis.openapi.models.operations.async.PageCountRequestBuilder;
import org.openapis.openapi.models.operations.async.PageCountResponse;
import org.openapis.openapi.models.operations.async.PageRotationRequestBuilder;
import org.openapis.openapi.models.operations.async.PageRotationResponse;
import org.openapis.openapi.models.operations.async.PageSizeRequestBuilder;
import org.openapis.openapi.models.operations.async.PageSizeResponse;
import org.openapis.openapi.operations.ContainsImage;
import org.openapis.openapi.operations.ContainsText;
import org.openapis.openapi.operations.FileSize;
import org.openapis.openapi.operations.PageCount;
import org.openapis.openapi.operations.PageRotation;
import org.openapis.openapi.operations.PageSize;
import org.openapis.openapi.utils.Headers;

/**
 * Document content filtering and search operations for information discovery and organization.
 * 
 * <p>This endpoint group enables intelligent content discovery and organization within
 * document collections for content-based processing and information extraction.
 * 
 * <p>Common use cases:
 * • Legal discovery, research organization, and compliance auditing
 * • Content moderation, academic research, and business intelligence
 * • Quality assurance and content validation workflows
 * 
 * <p>Business applications:
 * • Contract analysis, financial review, and healthcare records organization
 * • Government processing, educational curation, and IP protection
 * 
 * <p>Workflow scenarios:
 * • Large-scale processing, automated classification, and information extraction
 * • Document preparation for further processing or analysis
 * 
 * <p>Target users: Legal professionals, researchers, compliance officers, and
 * organizations requiring intelligent document content discovery and organization.
 */
public class AsyncFilter {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final Filter syncSDK;

    AsyncFilter(Filter syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public Filter sync() {
        return syncSDK;
    }


    /**
     * Checks if a PDF is of a certain size
     * 
     * <p>Input:PDF Output:Boolean Type:SISO
     * 
     * @return The async call builder
     */
    public PageSizeRequestBuilder pageSize() {
        return new PageSizeRequestBuilder(sdkConfiguration);
    }

    /**
     * Checks if a PDF is of a certain size
     * 
     * <p>Input:PDF Output:Boolean Type:SISO
     * 
     * @return CompletableFuture&lt;PageSizeResponse&gt; - The async response
     */
    public CompletableFuture<PageSizeResponse> pageSizeDirect() {
        return pageSize(null);
    }

    /**
     * Checks if a PDF is of a certain size
     * 
     * <p>Input:PDF Output:Boolean Type:SISO
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return CompletableFuture&lt;PageSizeResponse&gt; - The async response
     */
    public CompletableFuture<PageSizeResponse> pageSize(@Nullable PageSizeRequest request) {
        AsyncRequestOperation<PageSizeRequest, PageSizeResponse> operation
              = new PageSize.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Checks if a PDF is of a certain rotation
     * 
     * <p>Input:PDF Output:Boolean Type:SISO
     * 
     * @return The async call builder
     */
    public PageRotationRequestBuilder pageRotation() {
        return new PageRotationRequestBuilder(sdkConfiguration);
    }

    /**
     * Checks if a PDF is of a certain rotation
     * 
     * <p>Input:PDF Output:Boolean Type:SISO
     * 
     * @return CompletableFuture&lt;PageRotationResponse&gt; - The async response
     */
    public CompletableFuture<PageRotationResponse> pageRotationDirect() {
        return pageRotation(null);
    }

    /**
     * Checks if a PDF is of a certain rotation
     * 
     * <p>Input:PDF Output:Boolean Type:SISO
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return CompletableFuture&lt;PageRotationResponse&gt; - The async response
     */
    public CompletableFuture<PageRotationResponse> pageRotation(@Nullable PageRotationRequest request) {
        AsyncRequestOperation<PageRotationRequest, PageRotationResponse> operation
              = new PageRotation.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Checks if a PDF is greater, less or equal to a setPageCount
     * 
     * <p>Input:PDF Output:Boolean Type:SISO
     * 
     * @return The async call builder
     */
    public PageCountRequestBuilder pageCount() {
        return new PageCountRequestBuilder(sdkConfiguration);
    }

    /**
     * Checks if a PDF is greater, less or equal to a setPageCount
     * 
     * <p>Input:PDF Output:Boolean Type:SISO
     * 
     * @return CompletableFuture&lt;PageCountResponse&gt; - The async response
     */
    public CompletableFuture<PageCountResponse> pageCountDirect() {
        return pageCount(null);
    }

    /**
     * Checks if a PDF is greater, less or equal to a setPageCount
     * 
     * <p>Input:PDF Output:Boolean Type:SISO
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return CompletableFuture&lt;PageCountResponse&gt; - The async response
     */
    public CompletableFuture<PageCountResponse> pageCount(@Nullable PDFComparisonAndCount request) {
        AsyncRequestOperation<PDFComparisonAndCount, PageCountResponse> operation
              = new PageCount.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Checks if a PDF is a set file size
     * 
     * <p>Input:PDF Output:Boolean Type:SISO
     * 
     * @return The async call builder
     */
    public FileSizeRequestBuilder fileSize() {
        return new FileSizeRequestBuilder(sdkConfiguration);
    }

    /**
     * Checks if a PDF is a set file size
     * 
     * <p>Input:PDF Output:Boolean Type:SISO
     * 
     * @return CompletableFuture&lt;FileSizeResponse&gt; - The async response
     */
    public CompletableFuture<FileSizeResponse> fileSizeDirect() {
        return fileSize(null);
    }

    /**
     * Checks if a PDF is a set file size
     * 
     * <p>Input:PDF Output:Boolean Type:SISO
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return CompletableFuture&lt;FileSizeResponse&gt; - The async response
     */
    public CompletableFuture<FileSizeResponse> fileSize(@Nullable FileSizeRequest request) {
        AsyncRequestOperation<FileSizeRequest, FileSizeResponse> operation
              = new FileSize.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Checks if a PDF contains set text, returns true if does
     * 
     * <p>Input:PDF Output:Boolean Type:SISO
     * 
     * @return The async call builder
     */
    public ContainsTextRequestBuilder containsText() {
        return new ContainsTextRequestBuilder(sdkConfiguration);
    }

    /**
     * Checks if a PDF contains set text, returns true if does
     * 
     * <p>Input:PDF Output:Boolean Type:SISO
     * 
     * @return CompletableFuture&lt;ContainsTextResponse&gt; - The async response
     */
    public CompletableFuture<ContainsTextResponse> containsTextDirect() {
        return containsText(null);
    }

    /**
     * Checks if a PDF contains set text, returns true if does
     * 
     * <p>Input:PDF Output:Boolean Type:SISO
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return CompletableFuture&lt;ContainsTextResponse&gt; - The async response
     */
    public CompletableFuture<ContainsTextResponse> containsText(@Nullable ContainsTextRequest request) {
        AsyncRequestOperation<ContainsTextRequest, ContainsTextResponse> operation
              = new ContainsText.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Checks if a PDF contains an image
     * 
     * <p>Input:PDF Output:Boolean Type:SISO
     * 
     * @return The async call builder
     */
    public ContainsImageRequestBuilder containsImage() {
        return new ContainsImageRequestBuilder(sdkConfiguration);
    }

    /**
     * Checks if a PDF contains an image
     * 
     * <p>Input:PDF Output:Boolean Type:SISO
     * 
     * @return CompletableFuture&lt;ContainsImageResponse&gt; - The async response
     */
    public CompletableFuture<ContainsImageResponse> containsImageDirect() {
        return containsImage(null);
    }

    /**
     * Checks if a PDF contains an image
     * 
     * <p>Input:PDF Output:Boolean Type:SISO
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return CompletableFuture&lt;ContainsImageResponse&gt; - The async response
     */
    public CompletableFuture<ContainsImageResponse> containsImage(@Nullable PDFWithPageNums request) {
        AsyncRequestOperation<PDFWithPageNums, ContainsImageResponse> operation
              = new ContainsImage.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
