/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nullable;
import java.lang.Exception;
import org.openapis.openapi.models.components.AddAttachmentRequest;
import org.openapis.openapi.models.components.AddPageNumbersRequest;
import org.openapis.openapi.models.components.AddStampRequest;
import org.openapis.openapi.models.components.AutoSplitPdfRequest;
import org.openapis.openapi.models.components.ExtractHeaderRequest;
import org.openapis.openapi.models.components.ExtractImageScansRequest;
import org.openapis.openapi.models.components.FlattenRequest;
import org.openapis.openapi.models.components.MetadataRequest;
import org.openapis.openapi.models.components.OptimizePdfRequest;
import org.openapis.openapi.models.components.OverlayImageRequest;
import org.openapis.openapi.models.components.PDFExtractImagesRequest;
import org.openapis.openapi.models.components.PDFFile;
import org.openapis.openapi.models.components.ProcessPdfWithOcrRequest;
import org.openapis.openapi.models.components.RemoveBlankPagesRequest;
import org.openapis.openapi.models.components.ReplaceAndInvertColorRequest;
import org.openapis.openapi.models.components.ScannerEffectRequest;
import org.openapis.openapi.models.operations.AddAttachmentsRequestBuilder;
import org.openapis.openapi.models.operations.AddAttachmentsResponse;
import org.openapis.openapi.models.operations.AddPageNumbersRequestBuilder;
import org.openapis.openapi.models.operations.AddPageNumbersResponse;
import org.openapis.openapi.models.operations.AddStampRequestBuilder;
import org.openapis.openapi.models.operations.AddStampResponse;
import org.openapis.openapi.models.operations.AutoSplitPdfRequestBuilder;
import org.openapis.openapi.models.operations.AutoSplitPdfResponse;
import org.openapis.openapi.models.operations.DecompressPdfRequestBuilder;
import org.openapis.openapi.models.operations.DecompressPdfResponse;
import org.openapis.openapi.models.operations.ExtractHeader1RequestBuilder;
import org.openapis.openapi.models.operations.ExtractHeader1Response;
import org.openapis.openapi.models.operations.ExtractHeaderRequestBuilder;
import org.openapis.openapi.models.operations.ExtractHeaderResponse;
import org.openapis.openapi.models.operations.ExtractImageScansRequestBuilder;
import org.openapis.openapi.models.operations.ExtractImageScansResponse;
import org.openapis.openapi.models.operations.ExtractImagesRequestBuilder;
import org.openapis.openapi.models.operations.ExtractImagesResponse;
import org.openapis.openapi.models.operations.FlattenRequestBuilder;
import org.openapis.openapi.models.operations.FlattenResponse;
import org.openapis.openapi.models.operations.MetadataRequestBuilder;
import org.openapis.openapi.models.operations.MetadataResponse;
import org.openapis.openapi.models.operations.OptimizePdfRequestBuilder;
import org.openapis.openapi.models.operations.OptimizePdfResponse;
import org.openapis.openapi.models.operations.OverlayImageRequestBuilder;
import org.openapis.openapi.models.operations.OverlayImageResponse;
import org.openapis.openapi.models.operations.ProcessPdfWithOCRRequestBuilder;
import org.openapis.openapi.models.operations.ProcessPdfWithOCRResponse;
import org.openapis.openapi.models.operations.RemoveBlankPagesRequestBuilder;
import org.openapis.openapi.models.operations.RemoveBlankPagesResponse;
import org.openapis.openapi.models.operations.RepairPdfRequestBuilder;
import org.openapis.openapi.models.operations.RepairPdfResponse;
import org.openapis.openapi.models.operations.ReplaceAndInvertColorRequestBuilder;
import org.openapis.openapi.models.operations.ReplaceAndInvertColorResponse;
import org.openapis.openapi.models.operations.ScannerEffectRequestBuilder;
import org.openapis.openapi.models.operations.ScannerEffectResponse;
import org.openapis.openapi.models.operations.UnlockPDFFormsRequestBuilder;
import org.openapis.openapi.models.operations.UnlockPDFFormsResponse;
import org.openapis.openapi.operations.AddAttachments;
import org.openapis.openapi.operations.AddPageNumbers;
import org.openapis.openapi.operations.AddStamp;
import org.openapis.openapi.operations.AutoSplitPdf;
import org.openapis.openapi.operations.DecompressPdf;
import org.openapis.openapi.operations.ExtractHeader1;
import org.openapis.openapi.operations.ExtractHeader;
import org.openapis.openapi.operations.ExtractImageScans;
import org.openapis.openapi.operations.ExtractImages;
import org.openapis.openapi.operations.Flatten;
import org.openapis.openapi.operations.Metadata;
import org.openapis.openapi.operations.OptimizePdf;
import org.openapis.openapi.operations.OverlayImage;
import org.openapis.openapi.operations.ProcessPdfWithOCR;
import org.openapis.openapi.operations.RemoveBlankPages;
import org.openapis.openapi.operations.RepairPdf;
import org.openapis.openapi.operations.ReplaceAndInvertColor;
import org.openapis.openapi.operations.ScannerEffect;
import org.openapis.openapi.operations.UnlockPDFForms;
import org.openapis.openapi.utils.Headers;

/**
 * Specialized utilities and supplementary tools for enhanced document processing workflows.
 * 
 * <p>This endpoint group provides utility operations that support core document processing
 * tasks and address specific workflow needs in real-world scenarios.
 * 
 * <p>Common use cases:
 * • Document optimization for bandwidth-limited environments and storage cost management
 * • Document repair, content extraction, and validation for quality assurance
 * • Accessibility improvement and custom processing for specialized needs
 * 
 * <p>Business applications:
 * • Web publishing optimization, email attachment management, and archive efficiency
 * • Mobile compatibility, print production, and legacy document recovery
 * 
 * <p>Operational scenarios:
 * • Batch processing, quality control, and performance optimization
 * • Troubleshooting and recovery of problematic documents
 * 
 * <p>Target users: System administrators, document specialists, and organizations requiring
 * specialized document processing and optimization tools.
 */
public class Misc {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncMisc asyncSDK;

    Misc(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncMisc(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncMisc async() {
        return asyncSDK;
    }

    /**
     * Update metadata of a PDF file
     * 
     * <p>This endpoint allows you to update the metadata of a given PDF file. You can add, modify, or delete standard and custom metadata fields. Input:PDF Output:PDF Type:SISO
     * 
     * @return The call builder
     */
    public MetadataRequestBuilder metadata() {
        return new MetadataRequestBuilder(sdkConfiguration);
    }

    /**
     * Update metadata of a PDF file
     * 
     * <p>This endpoint allows you to update the metadata of a given PDF file. You can add, modify, or delete standard and custom metadata fields. Input:PDF Output:PDF Type:SISO
     * 
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public MetadataResponse metadataDirect() throws Exception {
        return metadata(null);
    }

    /**
     * Update metadata of a PDF file
     * 
     * <p>This endpoint allows you to update the metadata of a given PDF file. You can add, modify, or delete standard and custom metadata fields. Input:PDF Output:PDF Type:SISO
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public MetadataResponse metadata(@Nullable MetadataRequest request) throws Exception {
        RequestOperation<MetadataRequest, MetadataResponse> operation
              = new Metadata.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Remove read-only property from form fields
     * 
     * <p>Removing read-only property from form fields making them fillableInput:PDF, Output:PDF. Type:SISO
     * 
     * @return The call builder
     */
    public UnlockPDFFormsRequestBuilder unlockPDFForms() {
        return new UnlockPDFFormsRequestBuilder(sdkConfiguration);
    }

    /**
     * Remove read-only property from form fields
     * 
     * <p>Removing read-only property from form fields making them fillableInput:PDF, Output:PDF. Type:SISO
     * 
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public UnlockPDFFormsResponse unlockPDFFormsDirect() throws Exception {
        return unlockPDFForms(null);
    }

    /**
     * Remove read-only property from form fields
     * 
     * <p>Removing read-only property from form fields making them fillableInput:PDF, Output:PDF. Type:SISO
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public UnlockPDFFormsResponse unlockPDFForms(@Nullable PDFFile request) throws Exception {
        RequestOperation<PDFFile, UnlockPDFFormsResponse> operation
              = new UnlockPDFForms.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Grabs all JS from a PDF and returns a single JS file with all code
     * 
     * <p>desc. Input:PDF Output:JS Type:SISO
     * 
     * @return The call builder
     */
    public ExtractHeaderRequestBuilder extractHeader() {
        return new ExtractHeaderRequestBuilder(sdkConfiguration);
    }

    /**
     * Grabs all JS from a PDF and returns a single JS file with all code
     * 
     * <p>desc. Input:PDF Output:JS Type:SISO
     * 
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public ExtractHeaderResponse extractHeaderDirect() throws Exception {
        return extractHeader(null);
    }

    /**
     * Grabs all JS from a PDF and returns a single JS file with all code
     * 
     * <p>desc. Input:PDF Output:JS Type:SISO
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public ExtractHeaderResponse extractHeader(@Nullable PDFFile request) throws Exception {
        RequestOperation<PDFFile, ExtractHeaderResponse> operation
              = new ExtractHeader.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Apply scanner effect to PDF
     * 
     * <p>Applies various effects to simulate a scanned document, including rotation, noise, and edge softening. Input:PDF Output:PDF Type:SISO
     * 
     * @return The call builder
     */
    public ScannerEffectRequestBuilder scannerEffect() {
        return new ScannerEffectRequestBuilder(sdkConfiguration);
    }

    /**
     * Apply scanner effect to PDF
     * 
     * <p>Applies various effects to simulate a scanned document, including rotation, noise, and edge softening. Input:PDF Output:PDF Type:SISO
     * 
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public ScannerEffectResponse scannerEffectDirect() throws Exception {
        return scannerEffect(null);
    }

    /**
     * Apply scanner effect to PDF
     * 
     * <p>Applies various effects to simulate a scanned document, including rotation, noise, and edge softening. Input:PDF Output:PDF Type:SISO
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public ScannerEffectResponse scannerEffect(@Nullable ScannerEffectRequest request) throws Exception {
        RequestOperation<ScannerEffectRequest, ScannerEffectResponse> operation
              = new ScannerEffect.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Replace-Invert Color PDF
     * 
     * <p>This endpoint accepts a PDF file and option of invert all colors or replace text and background colors. Input:PDF Output:PDF Type:SISO
     * 
     * @return The call builder
     */
    public ReplaceAndInvertColorRequestBuilder replaceAndInvertColor() {
        return new ReplaceAndInvertColorRequestBuilder(sdkConfiguration);
    }

    /**
     * Replace-Invert Color PDF
     * 
     * <p>This endpoint accepts a PDF file and option of invert all colors or replace text and background colors. Input:PDF Output:PDF Type:SISO
     * 
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public ReplaceAndInvertColorResponse replaceAndInvertColorDirect() throws Exception {
        return replaceAndInvertColor(null);
    }

    /**
     * Replace-Invert Color PDF
     * 
     * <p>This endpoint accepts a PDF file and option of invert all colors or replace text and background colors. Input:PDF Output:PDF Type:SISO
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public ReplaceAndInvertColorResponse replaceAndInvertColor(@Nullable ReplaceAndInvertColorRequest request) throws Exception {
        RequestOperation<ReplaceAndInvertColorRequest, ReplaceAndInvertColorResponse> operation
              = new ReplaceAndInvertColor.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Repair a PDF file
     * 
     * <p>This endpoint repairs a given PDF file by running Ghostscript (primary), qpdf (fallback), or PDFBox (if no external tools available). The PDF is first saved to a temporary location, repaired, read back, and then returned as a response. Input:PDF Output:PDF Type:SISO
     * 
     * @return The call builder
     */
    public RepairPdfRequestBuilder repairPdf() {
        return new RepairPdfRequestBuilder(sdkConfiguration);
    }

    /**
     * Repair a PDF file
     * 
     * <p>This endpoint repairs a given PDF file by running Ghostscript (primary), qpdf (fallback), or PDFBox (if no external tools available). The PDF is first saved to a temporary location, repaired, read back, and then returned as a response. Input:PDF Output:PDF Type:SISO
     * 
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public RepairPdfResponse repairPdfDirect() throws Exception {
        return repairPdf(null);
    }

    /**
     * Repair a PDF file
     * 
     * <p>This endpoint repairs a given PDF file by running Ghostscript (primary), qpdf (fallback), or PDFBox (if no external tools available). The PDF is first saved to a temporary location, repaired, read back, and then returned as a response. Input:PDF Output:PDF Type:SISO
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public RepairPdfResponse repairPdf(@Nullable PDFFile request) throws Exception {
        RequestOperation<PDFFile, RepairPdfResponse> operation
              = new RepairPdf.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Remove blank pages from a PDF file
     * 
     * <p>This endpoint removes blank pages from a given PDF file. Users can specify the threshold and white percentage to tune the detection of blank pages. Input:PDF Output:PDF Type:SISO
     * 
     * @return The call builder
     */
    public RemoveBlankPagesRequestBuilder removeBlankPages() {
        return new RemoveBlankPagesRequestBuilder(sdkConfiguration);
    }

    /**
     * Remove blank pages from a PDF file
     * 
     * <p>This endpoint removes blank pages from a given PDF file. Users can specify the threshold and white percentage to tune the detection of blank pages. Input:PDF Output:PDF Type:SISO
     * 
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public RemoveBlankPagesResponse removeBlankPagesDirect() throws Exception {
        return removeBlankPages(null);
    }

    /**
     * Remove blank pages from a PDF file
     * 
     * <p>This endpoint removes blank pages from a given PDF file. Users can specify the threshold and white percentage to tune the detection of blank pages. Input:PDF Output:PDF Type:SISO
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public RemoveBlankPagesResponse removeBlankPages(@Nullable RemoveBlankPagesRequest request) throws Exception {
        RequestOperation<RemoveBlankPagesRequest, RemoveBlankPagesResponse> operation
              = new RemoveBlankPages.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Process a PDF file with OCR
     * 
     * <p>This endpoint processes a PDF file using OCR (Optical Character Recognition). Users can specify languages, sidecar, deskew, clean, cleanFinal, ocrType, ocrRenderType, and removeImagesAfter options. Uses OCRmyPDF if available, falls back to Tesseract. Input:PDF Output:PDF Type:SI-Conditional
     * 
     * @return The call builder
     */
    public ProcessPdfWithOCRRequestBuilder processPdfWithOCR() {
        return new ProcessPdfWithOCRRequestBuilder(sdkConfiguration);
    }

    /**
     * Process a PDF file with OCR
     * 
     * <p>This endpoint processes a PDF file using OCR (Optical Character Recognition). Users can specify languages, sidecar, deskew, clean, cleanFinal, ocrType, ocrRenderType, and removeImagesAfter options. Uses OCRmyPDF if available, falls back to Tesseract. Input:PDF Output:PDF Type:SI-Conditional
     * 
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public ProcessPdfWithOCRResponse processPdfWithOCRDirect() throws Exception {
        return processPdfWithOCR(null);
    }

    /**
     * Process a PDF file with OCR
     * 
     * <p>This endpoint processes a PDF file using OCR (Optical Character Recognition). Users can specify languages, sidecar, deskew, clean, cleanFinal, ocrType, ocrRenderType, and removeImagesAfter options. Uses OCRmyPDF if available, falls back to Tesseract. Input:PDF Output:PDF Type:SI-Conditional
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public ProcessPdfWithOCRResponse processPdfWithOCR(@Nullable ProcessPdfWithOcrRequest request) throws Exception {
        RequestOperation<ProcessPdfWithOcrRequest, ProcessPdfWithOCRResponse> operation
              = new ProcessPdfWithOCR.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Flatten PDF form fields or full page
     * 
     * <p>Flattening just PDF form fields or converting each page to images to make text unselectable. Input:PDF, Output:PDF. Type:SISO
     * 
     * @return The call builder
     */
    public FlattenRequestBuilder flatten() {
        return new FlattenRequestBuilder(sdkConfiguration);
    }

    /**
     * Flatten PDF form fields or full page
     * 
     * <p>Flattening just PDF form fields or converting each page to images to make text unselectable. Input:PDF, Output:PDF. Type:SISO
     * 
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public FlattenResponse flattenDirect() throws Exception {
        return flatten(null);
    }

    /**
     * Flatten PDF form fields or full page
     * 
     * <p>Flattening just PDF form fields or converting each page to images to make text unselectable. Input:PDF, Output:PDF. Type:SISO
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public FlattenResponse flatten(@Nullable FlattenRequest request) throws Exception {
        RequestOperation<FlattenRequest, FlattenResponse> operation
              = new Flatten.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Extract images from a PDF file
     * 
     * <p>This endpoint extracts images from a given PDF file and returns them in a zip file. Users can specify the output image format. Input:PDF Output:IMAGE/ZIP Type:SIMO
     * 
     * @return The call builder
     */
    public ExtractImagesRequestBuilder extractImages() {
        return new ExtractImagesRequestBuilder(sdkConfiguration);
    }

    /**
     * Extract images from a PDF file
     * 
     * <p>This endpoint extracts images from a given PDF file and returns them in a zip file. Users can specify the output image format. Input:PDF Output:IMAGE/ZIP Type:SIMO
     * 
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public ExtractImagesResponse extractImagesDirect() throws Exception {
        return extractImages(null);
    }

    /**
     * Extract images from a PDF file
     * 
     * <p>This endpoint extracts images from a given PDF file and returns them in a zip file. Users can specify the output image format. Input:PDF Output:IMAGE/ZIP Type:SIMO
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public ExtractImagesResponse extractImages(@Nullable PDFExtractImagesRequest request) throws Exception {
        RequestOperation<PDFExtractImagesRequest, ExtractImagesResponse> operation
              = new ExtractImages.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Extract image scans from an input file
     * 
     * <p>This endpoint extracts image scans from a given file based on certain parameters. Users can specify angle threshold, tolerance, minimum area, minimum contour area, and border size. Input:PDF Output:IMAGE/ZIP Type:SIMO
     * 
     * @return The call builder
     */
    public ExtractImageScansRequestBuilder extractImageScans() {
        return new ExtractImageScansRequestBuilder(sdkConfiguration);
    }

    /**
     * Extract image scans from an input file
     * 
     * <p>This endpoint extracts image scans from a given file based on certain parameters. Users can specify angle threshold, tolerance, minimum area, minimum contour area, and border size. Input:PDF Output:IMAGE/ZIP Type:SIMO
     * 
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public ExtractImageScansResponse extractImageScansDirect() throws Exception {
        return extractImageScans(null);
    }

    /**
     * Extract image scans from an input file
     * 
     * <p>This endpoint extracts image scans from a given file based on certain parameters. Users can specify angle threshold, tolerance, minimum area, minimum contour area, and border size. Input:PDF Output:IMAGE/ZIP Type:SIMO
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public ExtractImageScansResponse extractImageScans(@Nullable ExtractImageScansRequest request) throws Exception {
        RequestOperation<ExtractImageScansRequest, ExtractImageScansResponse> operation
              = new ExtractImageScans.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Decompress PDF streams
     * 
     * <p>Fully decompresses all PDF streams including text content
     * 
     * @return The call builder
     */
    public DecompressPdfRequestBuilder decompressPdf() {
        return new DecompressPdfRequestBuilder(sdkConfiguration);
    }

    /**
     * Decompress PDF streams
     * 
     * <p>Fully decompresses all PDF streams including text content
     * 
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public DecompressPdfResponse decompressPdfDirect() throws Exception {
        return decompressPdf(null);
    }

    /**
     * Decompress PDF streams
     * 
     * <p>Fully decompresses all PDF streams including text content
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public DecompressPdfResponse decompressPdf(@Nullable PDFFile request) throws Exception {
        RequestOperation<PDFFile, DecompressPdfResponse> operation
              = new DecompressPdf.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Optimize PDF file
     * 
     * <p>This endpoint accepts a PDF file and optimizes it based on the provided parameters. Input:PDF Output:PDF Type:SISO
     * 
     * @return The call builder
     */
    public OptimizePdfRequestBuilder optimizePdf() {
        return new OptimizePdfRequestBuilder(sdkConfiguration);
    }

    /**
     * Optimize PDF file
     * 
     * <p>This endpoint accepts a PDF file and optimizes it based on the provided parameters. Input:PDF Output:PDF Type:SISO
     * 
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public OptimizePdfResponse optimizePdfDirect() throws Exception {
        return optimizePdf(null);
    }

    /**
     * Optimize PDF file
     * 
     * <p>This endpoint accepts a PDF file and optimizes it based on the provided parameters. Input:PDF Output:PDF Type:SISO
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public OptimizePdfResponse optimizePdf(@Nullable OptimizePdfRequest request) throws Exception {
        RequestOperation<OptimizePdfRequest, OptimizePdfResponse> operation
              = new OptimizePdf.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Auto split PDF pages into separate documents
     * 
     * <p>This endpoint accepts a PDF file, scans each page for a specific QR code, and splits the document at the QR code boundaries. The output is a zip file containing each separate PDF document. Input:PDF Output:ZIP-PDF Type:SISO
     * 
     * @return The call builder
     */
    public AutoSplitPdfRequestBuilder autoSplitPdf() {
        return new AutoSplitPdfRequestBuilder(sdkConfiguration);
    }

    /**
     * Auto split PDF pages into separate documents
     * 
     * <p>This endpoint accepts a PDF file, scans each page for a specific QR code, and splits the document at the QR code boundaries. The output is a zip file containing each separate PDF document. Input:PDF Output:ZIP-PDF Type:SISO
     * 
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public AutoSplitPdfResponse autoSplitPdfDirect() throws Exception {
        return autoSplitPdf(null);
    }

    /**
     * Auto split PDF pages into separate documents
     * 
     * <p>This endpoint accepts a PDF file, scans each page for a specific QR code, and splits the document at the QR code boundaries. The output is a zip file containing each separate PDF document. Input:PDF Output:ZIP-PDF Type:SISO
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public AutoSplitPdfResponse autoSplitPdf(@Nullable AutoSplitPdfRequest request) throws Exception {
        RequestOperation<AutoSplitPdfRequest, AutoSplitPdfResponse> operation
              = new AutoSplitPdf.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Extract header from PDF file
     * 
     * <p>This endpoint accepts a PDF file and attempts to extract its title or header based on heuristics. Input:PDF Output:PDF Type:SISO
     * 
     * @return The call builder
     */
    public ExtractHeader1RequestBuilder extractHeader1() {
        return new ExtractHeader1RequestBuilder(sdkConfiguration);
    }

    /**
     * Extract header from PDF file
     * 
     * <p>This endpoint accepts a PDF file and attempts to extract its title or header based on heuristics. Input:PDF Output:PDF Type:SISO
     * 
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public ExtractHeader1Response extractHeader1Direct() throws Exception {
        return extractHeader1(null);
    }

    /**
     * Extract header from PDF file
     * 
     * <p>This endpoint accepts a PDF file and attempts to extract its title or header based on heuristics. Input:PDF Output:PDF Type:SISO
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public ExtractHeader1Response extractHeader1(@Nullable ExtractHeaderRequest request) throws Exception {
        RequestOperation<ExtractHeaderRequest, ExtractHeader1Response> operation
              = new ExtractHeader1.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Add stamp to a PDF file
     * 
     * <p>This endpoint adds a stamp to a given PDF file. Users can specify the stamp type (text or image), rotation, opacity, width spacer, and height spacer. Input:PDF Output:PDF Type:SISO
     * 
     * @return The call builder
     */
    public AddStampRequestBuilder addStamp() {
        return new AddStampRequestBuilder(sdkConfiguration);
    }

    /**
     * Add stamp to a PDF file
     * 
     * <p>This endpoint adds a stamp to a given PDF file. Users can specify the stamp type (text or image), rotation, opacity, width spacer, and height spacer. Input:PDF Output:PDF Type:SISO
     * 
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public AddStampResponse addStampDirect() throws Exception {
        return addStamp(null);
    }

    /**
     * Add stamp to a PDF file
     * 
     * <p>This endpoint adds a stamp to a given PDF file. Users can specify the stamp type (text or image), rotation, opacity, width spacer, and height spacer. Input:PDF Output:PDF Type:SISO
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public AddStampResponse addStamp(@Nullable AddStampRequest request) throws Exception {
        RequestOperation<AddStampRequest, AddStampResponse> operation
              = new AddStamp.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Add page numbers to a PDF document
     * 
     * <p>This operation takes an input PDF file and adds page numbers to it. Input:PDF Output:PDF Type:SISO
     * 
     * @return The call builder
     */
    public AddPageNumbersRequestBuilder addPageNumbers() {
        return new AddPageNumbersRequestBuilder(sdkConfiguration);
    }

    /**
     * Add page numbers to a PDF document
     * 
     * <p>This operation takes an input PDF file and adds page numbers to it. Input:PDF Output:PDF Type:SISO
     * 
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public AddPageNumbersResponse addPageNumbersDirect() throws Exception {
        return addPageNumbers(null);
    }

    /**
     * Add page numbers to a PDF document
     * 
     * <p>This operation takes an input PDF file and adds page numbers to it. Input:PDF Output:PDF Type:SISO
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public AddPageNumbersResponse addPageNumbers(@Nullable AddPageNumbersRequest request) throws Exception {
        RequestOperation<AddPageNumbersRequest, AddPageNumbersResponse> operation
              = new AddPageNumbers.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Overlay image onto a PDF file
     * 
     * <p>This endpoint overlays an image onto a PDF file at the specified coordinates. The image can be overlaid on every page of the PDF if specified.  Input:PDF/IMAGE Output:PDF Type:SISO
     * 
     * @return The call builder
     */
    public OverlayImageRequestBuilder overlayImage() {
        return new OverlayImageRequestBuilder(sdkConfiguration);
    }

    /**
     * Overlay image onto a PDF file
     * 
     * <p>This endpoint overlays an image onto a PDF file at the specified coordinates. The image can be overlaid on every page of the PDF if specified.  Input:PDF/IMAGE Output:PDF Type:SISO
     * 
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public OverlayImageResponse overlayImageDirect() throws Exception {
        return overlayImage(null);
    }

    /**
     * Overlay image onto a PDF file
     * 
     * <p>This endpoint overlays an image onto a PDF file at the specified coordinates. The image can be overlaid on every page of the PDF if specified.  Input:PDF/IMAGE Output:PDF Type:SISO
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public OverlayImageResponse overlayImage(@Nullable OverlayImageRequest request) throws Exception {
        RequestOperation<OverlayImageRequest, OverlayImageResponse> operation
              = new OverlayImage.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Add attachments to PDF
     * 
     * <p>This endpoint adds attachments to a PDF. Input:PDF, Output:PDF Type:MISO
     * 
     * @return The call builder
     */
    public AddAttachmentsRequestBuilder addAttachments() {
        return new AddAttachmentsRequestBuilder(sdkConfiguration);
    }

    /**
     * Add attachments to PDF
     * 
     * <p>This endpoint adds attachments to a PDF. Input:PDF, Output:PDF Type:MISO
     * 
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public AddAttachmentsResponse addAttachmentsDirect() throws Exception {
        return addAttachments(null);
    }

    /**
     * Add attachments to PDF
     * 
     * <p>This endpoint adds attachments to a PDF. Input:PDF, Output:PDF Type:MISO
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public AddAttachmentsResponse addAttachments(@Nullable AddAttachmentRequest request) throws Exception {
        RequestOperation<AddAttachmentRequest, AddAttachmentsResponse> operation
              = new AddAttachments.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
