workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Stirling PDF - Processing API:
        inputs:
            - location: api.yml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/stirling-pdf/stirling/stirling-pdf---processing-api
targets:
    stirling-pdf:
        target: java
        source: Stirling PDF - Processing API
        publish:
            java:
                ossrhUsername: $ossrh_username
                ossrhPassword: $ossrh_password
                gpgSecretKey: $java_gpg_secret_key
                gpgPassPhrase: $java_gpg_passphrase
