/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import org.openapis.openapi.utils.SpeakeasyMetadata;
import org.openapis.openapi.utils.Utils;


public class AddAttachmentRequest {

    @SpeakeasyMetadata("multipartForm:file,name=fileInput")
    private AddAttachmentRequestFileInput fileInput;

    /**
     * File ID for server-side files (can be used instead of fileInput)
     */
    @SpeakeasyMetadata("multipartForm:name=fileId")
    private String fileId;

    /**
     * The image file to be overlaid onto the PDF.
     */
    @SpeakeasyMetadata("multipartForm:file,name=attachments")
    private List<Attachment> attachments;

    @JsonCreator
    public AddAttachmentRequest(
            @Nullable AddAttachmentRequestFileInput fileInput,
            @Nullable String fileId,
            @Nonnull List<Attachment> attachments) {
        this.fileInput = fileInput;
        this.fileId = fileId;
        this.attachments = Optional.ofNullable(attachments)
            .orElseThrow(() -> new IllegalArgumentException("attachments cannot be null"));
    }
    
    public AddAttachmentRequest(
            @Nonnull List<Attachment> attachments) {
        this(null, null, attachments);
    }

    public Optional<AddAttachmentRequestFileInput> fileInput() {
        return Optional.ofNullable(this.fileInput);
    }

    /**
     * File ID for server-side files (can be used instead of fileInput)
     */
    public Optional<String> fileId() {
        return Optional.ofNullable(this.fileId);
    }

    /**
     * The image file to be overlaid onto the PDF.
     */
    public List<Attachment> attachments() {
        return this.attachments;
    }

    public static Builder builder() {
        return new Builder();
    }


    public AddAttachmentRequest withFileInput(@Nullable AddAttachmentRequestFileInput fileInput) {
        this.fileInput = fileInput;
        return this;
    }


    /**
     * File ID for server-side files (can be used instead of fileInput)
     */
    public AddAttachmentRequest withFileId(@Nullable String fileId) {
        this.fileId = fileId;
        return this;
    }


    /**
     * The image file to be overlaid onto the PDF.
     */
    public AddAttachmentRequest withAttachments(@Nonnull List<Attachment> attachments) {
        this.attachments = Utils.checkNotNull(attachments, "attachments");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AddAttachmentRequest other = (AddAttachmentRequest) o;
        return 
            Utils.enhancedDeepEquals(this.fileInput, other.fileInput) &&
            Utils.enhancedDeepEquals(this.fileId, other.fileId) &&
            Utils.enhancedDeepEquals(this.attachments, other.attachments);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            fileInput, fileId, attachments);
    }
    
    @Override
    public String toString() {
        return Utils.toString(AddAttachmentRequest.class,
                "fileInput", fileInput,
                "fileId", fileId,
                "attachments", attachments);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private AddAttachmentRequestFileInput fileInput;

        private String fileId;

        private List<Attachment> attachments;

        private Builder() {
          // force use of static builder() method
        }

        public Builder fileInput(@Nullable AddAttachmentRequestFileInput fileInput) {
            this.fileInput = fileInput;
            return this;
        }

        /**
         * File ID for server-side files (can be used instead of fileInput)
         */
        public Builder fileId(@Nullable String fileId) {
            this.fileId = fileId;
            return this;
        }

        /**
         * The image file to be overlaid onto the PDF.
         */
        public Builder attachments(@Nonnull List<Attachment> attachments) {
            this.attachments = Utils.checkNotNull(attachments, "attachments");
            return this;
        }

        public AddAttachmentRequest build() {
            return new AddAttachmentRequest(
                fileInput, fileId, attachments);
        }

    }
}
