/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * AddWatermarkRequestAlphabet
 * 
 * <p>The selected alphabet
 */
public enum AddWatermarkRequestAlphabet {
    ROMAN("roman"),
    ARABIC("arabic"),
    JAPANESE("japanese"),
    KOREAN("korean"),
    CHINESE("chinese");

    @JsonValue
    private final String value;

    AddWatermarkRequestAlphabet(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<AddWatermarkRequestAlphabet> fromValue(String value) {
        for (AddWatermarkRequestAlphabet o: AddWatermarkRequestAlphabet.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

