/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;
import java.util.Optional;

/**
 * Angle
 * 
 * <p>The angle by which to rotate the PDF file. This should be a multiple of 90.
 */
public enum Angle {
    ZERO(0),
    NINETY(90),
    ONE_HUNDRED_AND_EIGHTY(180),
    TWO_HUNDRED_AND_SEVENTY(270);

    @JsonValue
    private final int value;

    Angle(int value) {
        this.value = value;
    }
    
    public int value() {
        return value;
    }
    
    public static Optional<Angle> fromValue(int value) {
        for (Angle o: Angle.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

