/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * BookletType
 * 
 * <p>The booklet type to create.
 */
public enum BookletType {
    BOOKLET("BOOKLET"),
    SIDE_STITCH_BOOKLET("SIDE_STITCH_BOOKLET");

    @JsonValue
    private final String value;

    BookletType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<BookletType> fromValue(String value) {
        for (BookletType o: BookletType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

