/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * ConvertToPdfRequestColorType
 * 
 * <p>The color type of the output image(s)
 */
public enum ConvertToPdfRequestColorType {
    COLOR("color"),
    GREYSCALE("greyscale"),
    BLACKWHITE("blackwhite");

    @JsonValue
    private final String value;

    ConvertToPdfRequestColorType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<ConvertToPdfRequestColorType> fromValue(String value) {
        for (ConvertToPdfRequestColorType o: ConvertToPdfRequestColorType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

