/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * HighContrastColorCombination
 * 
 * <p>If HIGH_CONTRAST_COLOR option selected, then pick the default color option for text and background.
 */
public enum HighContrastColorCombination {
    WHITE_TEXT_ON_BLACK("WHITE_TEXT_ON_BLACK"),
    BLACK_TEXT_ON_WHITE("BLACK_TEXT_ON_WHITE"),
    YELLOW_TEXT_ON_BLACK("YELLOW_TEXT_ON_BLACK"),
    GREEN_TEXT_ON_BLACK("GREEN_TEXT_ON_BLACK");

    @JsonValue
    private final String value;

    HighContrastColorCombination(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<HighContrastColorCombination> fromValue(String value) {
        for (HighContrastColorCombination o: HighContrastColorCombination.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

