/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;
import java.util.Optional;

/**
 * KeyLength
 * 
 * <p>The length of the encryption key
 */
public enum KeyLength {
    FORTY(40),
    ONE_HUNDRED_AND_TWENTY_EIGHT(128),
    TWO_HUNDRED_AND_FIFTY_SIX(256);

    @JsonValue
    private final int value;

    KeyLength(int value) {
        this.value = value;
    }
    
    public int value() {
        return value;
    }
    
    public static Optional<KeyLength> fromValue(int value) {
        for (KeyLength o: KeyLength.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

