/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;
import java.util.Optional;

/**
 * MergeMultiplePagesRequestPagesPerSheet
 * 
 * <p>The number of pages to fit onto a single sheet in the output PDF.
 */
public enum MergeMultiplePagesRequestPagesPerSheet {
    TWO(2),
    THREE(3),
    FOUR(4),
    NINE(9),
    SIXTEEN(16);

    @JsonValue
    private final int value;

    MergeMultiplePagesRequestPagesPerSheet(int value) {
        this.value = value;
    }
    
    public int value() {
        return value;
    }
    
    public static Optional<MergeMultiplePagesRequestPagesPerSheet> fromValue(int value) {
        for (MergeMultiplePagesRequestPagesPerSheet o: MergeMultiplePagesRequestPagesPerSheet.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

