/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.SpeakeasyMetadata;
import org.openapis.openapi.utils.Utils;


public class MergeMultiplePagesRequest {

    @SpeakeasyMetadata("multipartForm:file,name=fileInput")
    private MergeMultiplePagesRequestFileInput fileInput;

    /**
     * File ID for server-side files (can be used instead of fileInput)
     */
    @SpeakeasyMetadata("multipartForm:name=fileId")
    private String fileId;

    /**
     * The number of pages to fit onto a single sheet in the output PDF.
     */
    @SpeakeasyMetadata("multipartForm:name=pagesPerSheet")
    private MergeMultiplePagesRequestPagesPerSheet pagesPerSheet;

    /**
     * Boolean for if you wish to add border around the pages
     */
    @SpeakeasyMetadata("multipartForm:name=addBorder")
    private Boolean addBorder;

    @JsonCreator
    public MergeMultiplePagesRequest(
            @Nullable MergeMultiplePagesRequestFileInput fileInput,
            @Nullable String fileId,
            @Nonnull MergeMultiplePagesRequestPagesPerSheet pagesPerSheet,
            @Nullable Boolean addBorder) {
        this.fileInput = fileInput;
        this.fileId = fileId;
        this.pagesPerSheet = Optional.ofNullable(pagesPerSheet)
            .orElseThrow(() -> new IllegalArgumentException("pagesPerSheet cannot be null"));
        this.addBorder = addBorder;
    }
    
    public MergeMultiplePagesRequest(
            @Nonnull MergeMultiplePagesRequestPagesPerSheet pagesPerSheet) {
        this(null, null, pagesPerSheet,
            null);
    }

    public Optional<MergeMultiplePagesRequestFileInput> fileInput() {
        return Optional.ofNullable(this.fileInput);
    }

    /**
     * File ID for server-side files (can be used instead of fileInput)
     */
    public Optional<String> fileId() {
        return Optional.ofNullable(this.fileId);
    }

    /**
     * The number of pages to fit onto a single sheet in the output PDF.
     */
    public MergeMultiplePagesRequestPagesPerSheet pagesPerSheet() {
        return this.pagesPerSheet;
    }

    /**
     * Boolean for if you wish to add border around the pages
     */
    public Optional<Boolean> addBorder() {
        return Optional.ofNullable(this.addBorder);
    }

    public static Builder builder() {
        return new Builder();
    }


    public MergeMultiplePagesRequest withFileInput(@Nullable MergeMultiplePagesRequestFileInput fileInput) {
        this.fileInput = fileInput;
        return this;
    }


    /**
     * File ID for server-side files (can be used instead of fileInput)
     */
    public MergeMultiplePagesRequest withFileId(@Nullable String fileId) {
        this.fileId = fileId;
        return this;
    }


    /**
     * The number of pages to fit onto a single sheet in the output PDF.
     */
    public MergeMultiplePagesRequest withPagesPerSheet(@Nonnull MergeMultiplePagesRequestPagesPerSheet pagesPerSheet) {
        this.pagesPerSheet = Utils.checkNotNull(pagesPerSheet, "pagesPerSheet");
        return this;
    }


    /**
     * Boolean for if you wish to add border around the pages
     */
    public MergeMultiplePagesRequest withAddBorder(@Nullable Boolean addBorder) {
        this.addBorder = addBorder;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MergeMultiplePagesRequest other = (MergeMultiplePagesRequest) o;
        return 
            Utils.enhancedDeepEquals(this.fileInput, other.fileInput) &&
            Utils.enhancedDeepEquals(this.fileId, other.fileId) &&
            Utils.enhancedDeepEquals(this.pagesPerSheet, other.pagesPerSheet) &&
            Utils.enhancedDeepEquals(this.addBorder, other.addBorder);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            fileInput, fileId, pagesPerSheet,
            addBorder);
    }
    
    @Override
    public String toString() {
        return Utils.toString(MergeMultiplePagesRequest.class,
                "fileInput", fileInput,
                "fileId", fileId,
                "pagesPerSheet", pagesPerSheet,
                "addBorder", addBorder);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private MergeMultiplePagesRequestFileInput fileInput;

        private String fileId;

        private MergeMultiplePagesRequestPagesPerSheet pagesPerSheet;

        private Boolean addBorder;

        private Builder() {
          // force use of static builder() method
        }

        public Builder fileInput(@Nullable MergeMultiplePagesRequestFileInput fileInput) {
            this.fileInput = fileInput;
            return this;
        }

        /**
         * File ID for server-side files (can be used instead of fileInput)
         */
        public Builder fileId(@Nullable String fileId) {
            this.fileId = fileId;
            return this;
        }

        /**
         * The number of pages to fit onto a single sheet in the output PDF.
         */
        public Builder pagesPerSheet(@Nonnull MergeMultiplePagesRequestPagesPerSheet pagesPerSheet) {
            this.pagesPerSheet = Utils.checkNotNull(pagesPerSheet, "pagesPerSheet");
            return this;
        }

        /**
         * Boolean for if you wish to add border around the pages
         */
        public Builder addBorder(@Nullable Boolean addBorder) {
            this.addBorder = addBorder;
            return this;
        }

        public MergeMultiplePagesRequest build() {
            return new MergeMultiplePagesRequest(
                fileInput, fileId, pagesPerSheet,
                addBorder);
        }

    }
}
