/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * OcrRenderType
 * 
 * <p>Specify the OCR render type, either 'hocr' or 'sandwich'
 */
public enum OcrRenderType {
    HOCR("hocr"),
    SANDWICH("sandwich");

    @JsonValue
    private final String value;

    OcrRenderType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<OcrRenderType> fromValue(String value) {
        for (OcrRenderType o: OcrRenderType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

