/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * OcrType
 * 
 * <p>Specify the OCR type, e.g., 'skip-text', 'force-ocr', or 'Normal'
 */
public enum OcrType {
    SKIP_TEXT("skip-text"),
    FORCE_OCR("force-ocr"),
    NORMAL("Normal");

    @JsonValue
    private final String value;

    OcrType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<OcrType> fromValue(String value) {
        for (OcrType o: OcrType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

