/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;
import java.util.Optional;

/**
 * OptimizeLevel
 * 
 * <p>The level of optimization to apply to the PDF file. Higher values indicate greater compression but may reduce quality.
 */
public enum OptimizeLevel {
    ONE(1),
    TWO(2),
    THREE(3),
    FOUR(4),
    FIVE(5),
    SIX(6),
    SEVEN(7),
    EIGHT(8),
    NINE(9);

    @JsonValue
    private final int value;

    OptimizeLevel(int value) {
        this.value = value;
    }
    
    public int value() {
        return value;
    }
    
    public static Optional<OptimizeLevel> fromValue(int value) {
        for (OptimizeLevel o: OptimizeLevel.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

