/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * PageSizeRequestComparator
 * 
 * <p>The comparison type, accepts Greater, Equal, Less than
 */
public enum PageSizeRequestComparator {
    GREATER("Greater"),
    EQUAL("Equal"),
    LESS("Less");

    @JsonValue
    private final String value;

    PageSizeRequestComparator(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<PageSizeRequestComparator> fromValue(String value) {
        for (PageSizeRequestComparator o: PageSizeRequestComparator.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

