/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * PageSize
 * 
 * <p>The scale of pages in the output PDF. Acceptable values are A0-A6, LETTER, LEGAL, KEEP.
 */
public enum PageSize {
    A0("A0"),
    A1("A1"),
    A2("A2"),
    A3("A3"),
    A4("A4"),
    A5("A5"),
    A6("A6"),
    LETTER("LETTER"),
    LEGAL("LEGAL"),
    KEEP("KEEP");

    @JsonValue
    private final String value;

    PageSize(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<PageSize> fromValue(String value) {
        for (PageSize o: PageSize.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

