/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.SpeakeasyMetadata;
import org.openapis.openapi.utils.Utils;


public class PDFPasswordRequest {

    @SpeakeasyMetadata("multipartForm:file,name=fileInput")
    private PDFPasswordRequestFileInput fileInput;

    /**
     * File ID for server-side files (can be used instead of fileInput)
     */
    @SpeakeasyMetadata("multipartForm:name=fileId")
    private String fileId;

    /**
     * The password of the PDF file
     */
    @SpeakeasyMetadata("multipartForm:name=password")
    private String password;

    @JsonCreator
    public PDFPasswordRequest(
            @Nullable PDFPasswordRequestFileInput fileInput,
            @Nullable String fileId,
            @Nullable String password) {
        this.fileInput = fileInput;
        this.fileId = fileId;
        this.password = password;
    }
    
    public PDFPasswordRequest() {
        this(null, null, null);
    }

    public Optional<PDFPasswordRequestFileInput> fileInput() {
        return Optional.ofNullable(this.fileInput);
    }

    /**
     * File ID for server-side files (can be used instead of fileInput)
     */
    public Optional<String> fileId() {
        return Optional.ofNullable(this.fileId);
    }

    /**
     * The password of the PDF file
     */
    public Optional<String> password() {
        return Optional.ofNullable(this.password);
    }

    public static Builder builder() {
        return new Builder();
    }


    public PDFPasswordRequest withFileInput(@Nullable PDFPasswordRequestFileInput fileInput) {
        this.fileInput = fileInput;
        return this;
    }


    /**
     * File ID for server-side files (can be used instead of fileInput)
     */
    public PDFPasswordRequest withFileId(@Nullable String fileId) {
        this.fileId = fileId;
        return this;
    }


    /**
     * The password of the PDF file
     */
    public PDFPasswordRequest withPassword(@Nullable String password) {
        this.password = password;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PDFPasswordRequest other = (PDFPasswordRequest) o;
        return 
            Utils.enhancedDeepEquals(this.fileInput, other.fileInput) &&
            Utils.enhancedDeepEquals(this.fileId, other.fileId) &&
            Utils.enhancedDeepEquals(this.password, other.password);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            fileInput, fileId, password);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PDFPasswordRequest.class,
                "fileInput", fileInput,
                "fileId", fileId,
                "password", password);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private PDFPasswordRequestFileInput fileInput;

        private String fileId;

        private String password;

        private Builder() {
          // force use of static builder() method
        }

        public Builder fileInput(@Nullable PDFPasswordRequestFileInput fileInput) {
            this.fileInput = fileInput;
            return this;
        }

        /**
         * File ID for server-side files (can be used instead of fileInput)
         */
        public Builder fileId(@Nullable String fileId) {
            this.fileId = fileId;
            return this;
        }

        /**
         * The password of the PDF file
         */
        public Builder password(@Nullable String password) {
            this.password = password;
            return this;
        }

        public PDFPasswordRequest build() {
            return new PDFPasswordRequest(
                fileInput, fileId, password);
        }

    }
}
