/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * PdfToTextOrRTFRequestOutputFormat
 * 
 * <p>The output Text or RTF format
 */
public enum PdfToTextOrRTFRequestOutputFormat {
    RTF("rtf"),
    TXT("txt");

    @JsonValue
    private final String value;

    PdfToTextOrRTFRequestOutputFormat(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<PdfToTextOrRTFRequestOutputFormat> fromValue(String value) {
        for (PdfToTextOrRTFRequestOutputFormat o: PdfToTextOrRTFRequestOutputFormat.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

