/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * ReplaceAndInvertOption
 * 
 * <p>Replace and Invert color options of a pdf.
 */
public enum ReplaceAndInvertOption {
    HIGH_CONTRAST_COLOR("HIGH_CONTRAST_COLOR"),
    CUSTOM_COLOR("CUSTOM_COLOR"),
    FULL_INVERSION("FULL_INVERSION");

    @JsonValue
    private final String value;

    ReplaceAndInvertOption(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<ReplaceAndInvertOption> fromValue(String value) {
        for (ReplaceAndInvertOption o: ReplaceAndInvertOption.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

