/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * Trapped
 * 
 * <p>The trapped status of the document
 */
public enum Trapped {
    TRUE("True"),
    FALSE("False"),
    UNKNOWN("Unknown");

    @JsonValue
    private final String value;

    Trapped(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<Trapped> fromValue(String value) {
        for (Trapped o: Trapped.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

